ci: upload App Distribution

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -146,6 +146,14 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
+      - name: Check if APK exists
+        run: |
+          if [ ! -f app/build/outputs/apk/debug/app-debug.apk ]; then
+            echo "APK not found!"
+            exit 1
+          fi
+          
+
       - name: Upload APK as artifact
         uses: actions/upload-artifact@v4
         with:
